name: Dual Publish (npm + GitHub Packages)

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Set package name for npm
        run: npm pkg set name="language-styler"

      - name: Publish to npm
        run: npm publish --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@eyachirarafat'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@eyachirarafat:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_LS_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Set package name for GitHub Packages
        run: npm pkg set name="@eyachirarafat/language-styler"

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_LS_TOKEN }}